version: "3"

services:
  app:
    build: .
    command: yarn dev
    ports:
      - "3002:3002"
    environment:
      - DB_HOST=dbpostgres
    volumes:
      - ".:/usr/app"
      
  dbpostgres:
    image: "postgres" 
    env_file:
      - .env
    volumes:
      - database-data:/var/lib/postgresql/data2/

volumes:
  database-data: